trigger:
- main

resources:
  repositories:
    - repository: ai_repo
      name: py-azurefunc-iep-2-ai
    - repository: backend_repo
      name: py-azurefunc-iep-backend-1
    - repository: frontend_repo
      name: js-swa-iep-portal-frontend-1

pool:
  vmImage: 'ubuntu-latest'

stages:

# STAGE 1: PLAN
- stage: Build_Plan
  displayName: "1. Terraform Plan"
  jobs:
  - job: PlanJob
    steps:
    - checkout: self
    - script: |
        terraform init
        terraform plan -out=main.tfplan
      displayName: 'Create Plan'
      env:
        ARM_SUBSCRIPTION_ID: $(sub_id) #add these variables in UI
        ARM_CLIENT_ID: $(client_id)
        ARM_CLIENT_SECRET: $(client_secret)
        ARM_TENANT_ID: $(tenant_id)

# STAGE 2: APPROVAL
- stage: Approval
  displayName: "2. Review"
  dependsOn: Build_Plan
  jobs:
  - job: WaitForReview
    pool: server # Required for ManualValidation
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: 'admin@example.com' #set responsible person
        instructions: 'Check the Plan logs. If it looks good, click Resume.'

# STAGE 3: DEPLOY
- stage: Deploy_Infrastructure_And_Apps
  displayName: "3. Deploy Everything"
  dependsOn: Approval
  jobs:
  - job: DeployJob
    steps:
    - checkout: self
    - checkout: ai_repo
    - checkout: backend_repo
    - checkout: frontend_repo

    - script: |
        terraform init
        terraform apply -auto-approve
      displayName: 'Apply Terraform'
      env:
        ARM_SUBSCRIPTION_ID: $(sub_id)
        ARM_CLIENT_ID: $(client_id)
        ARM_CLIENT_SECRET: $(client_secret)
        ARM_TENANT_ID: $(tenant_id)

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'MyServiceConnection'
        appName: 'iep-2-ai'
        package: '$(Agent.BuildDirectory)/ai_repo'

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: 'MyServiceConnection'
        appName: 'iep-backend'
        package: '$(Agent.BuildDirectory)/backend_repo'

    - task: AzureStaticWebApp@0
      inputs:
        app_location: '/frontend_repo'
        azure_static_web_apps_api_token: $(SWA_TOKEN)